apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insighthub.fullname" . }}-app
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.app.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
