apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "insighthub.fullname" . }}-aws
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "insighthub.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secretsStore.region | quote }}
    objects: |
      - objectName: {{ required "secretsStore.rdsSecretArn is required" .Values.secretsStore.rdsSecretArn | quote }}
        objectType: secretsmanager
        objectAlias: rds.json
      - objectName: {{ required "secretsStore.redisSecretArn is required" .Values.secretsStore.redisSecretArn | quote }}
        objectType: secretsmanager
        objectAlias: redis.json
